info:
  id: ${spring.application.name}
---
spring:
  profiles: openshift
logging:
  file: ${OPENSHIFT_LOG_DIR}/openshift_discovery-service_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: DEBUG
    org.ihkhan: DEBUG
    org.hibernate: DEBUG
---
spring:
  profiles: production
logging:
  file: ${OPENSHIFT_LOG_DIR}/production_discovery-service_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    org.ihkhan: WARN
    org.hibernate: WARN