info:
  id: ${spring.application.name}
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  profiles: openshift
logging:
  file: ${OPENSHIFT_LOG_DIR}/openshift-service_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: WARN
    org.ihkhan: WARN
    org.hibernate: WARN
---
spring:
  profiles: production
logging:
  file: ${OPENSHIFT_LOG_DIR}/production-service_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    org.ihkhan: WARN
    org.hibernate: WARN
---
spring:
  profiles: dev
logging:
  file: logs/dev-service_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: DEBUG
    org.ihkhan: DEBUG
    org.hibernate: DEBUG         